### ISSUE TITLE
cheers

### ISSUE THREAD

**Issue by bounceme** [amadeus/vim-misc#1]
<img width="1249" alt="screen shot 2018-04-29 at 2 10 53 am" src="https://user-images.githubusercontent.com/9332107/39405070-ea4f1164-4b52-11e8-8101-d23c590cf538.png">

Just aknowledging all our work. fun times, haha

**Comment by bounceme** [comment]
one love ( expert vimscript !!! ) !

**Comment by amadeus** [comment]
Oh man, I totally missed this! 

Haha yeah, we've basically rewritten this thing a ton! It's come along way since before we started working on it.

I think expert might be a bit pushing it, I am certainly no Tim Pope xD

**Comment by bounceme** [comment]
https://www.youtube.com/watch?v=GryTcUIcTUQ
hrmmph
